
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shoicfistqgzjdvkfacn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNob2ljZmlzdHFnempkdmtmYWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjY0MzcsImV4cCI6MjA2MzU0MjQzN30.AO1eDv0kbI1ruZKBmDebiPdye12YQfFh_q77U4Roef4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
